import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const sliders = [
  {
    name: "P800 Taşınabilir Güç İstasyonu",
    badge: "Yeni Ürün",
    badgeIcon: "zap",
    title: "Kompakt Güç, Sınırsız Özgürlük",
    titleHighlight: "P800 Power Station",
    subtitle: "",
    buttonText: "Ürünü İncele",
    buttonLink: "/urun/p800",
    buttonStyle: "PRIMARY" as const,
    button2Text: "Tüm Ürünler",
    button2Link: "/magaza",
    button2Style: "SECONDARY" as const,
    desktopImage: "/sliders/slider-yatay-p800.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.8)",
    badgeBgColor: "rgba(16,185,129,0.2)",
    badgeTextColor: "#10b981",
    buttonBgColor: "#FFFFFF",
    buttonTextColor: "#000000",
    button2BgColor: "rgba(255,255,255,0.1)",
    button2TextColor: "#FFFFFF",
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(16,185,129,0.1)",
    badgeTextColorLight: "#059669",
    buttonBgColorLight: "#111827",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: "rgba(0,0,0,0.05)",
    button2TextColorLight: "#111827",
    titleHighlightFrom: "#10b981",
    titleHighlightTo: "#06b6d4",
    titleHighlightFromLight: "#059669",
    titleHighlightToLight: "#0891b2",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 0,
  },
  {
    name: "P1800 Profesyonel Güç İstasyonu",
    badge: "En Çok Satan",
    badgeIcon: "fire",
    title: "Profesyonel Güç Çözümü",
    titleHighlight: "P1800 Power Station",
    subtitle: "",
    buttonText: "Detayları Gör",
    buttonLink: "/urun/p1800",
    buttonStyle: "PRIMARY" as const,
    button2Text: "Karşılaştır",
    button2Link: "/karsilastir",
    button2Style: "OUTLINE" as const,
    desktopImage: "/sliders/slider-yatay-p1800.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.8)",
    badgeBgColor: "rgba(239,68,68,0.2)",
    badgeTextColor: "#f87171",
    buttonBgColor: "#10b981",
    buttonTextColor: "#FFFFFF",
    button2BgColor: "transparent",
    button2TextColor: "#FFFFFF",
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(239,68,68,0.1)",
    badgeTextColorLight: "#dc2626",
    buttonBgColorLight: "#10b981",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: "transparent",
    button2TextColorLight: "#111827",
    titleHighlightFrom: "#f59e0b",
    titleHighlightTo: "#ef4444",
    titleHighlightFromLight: "#d97706",
    titleHighlightToLight: "#dc2626",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 1,
  },
  {
    name: "P1800 Sahada Kullanım",
    badge: "Sahada Güç",
    badgeIcon: "truck",
    title: "Sahada Kesintisiz Enerji",
    titleHighlight: "P1800 ile Çalışın",
    subtitle: "",
    buttonText: "İncele",
    buttonLink: "/urun/p1800",
    buttonStyle: "PRIMARY" as const,
    button2Text: "",
    button2Link: "",
    button2Style: "SECONDARY" as const,
    desktopImage: "/sliders/slider-yatay-p1800-2.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.75)",
    badgeBgColor: "rgba(59,130,246,0.2)",
    badgeTextColor: "#60a5fa",
    buttonBgColor: "#FFFFFF",
    buttonTextColor: "#000000",
    button2BgColor: null,
    button2TextColor: null,
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(59,130,246,0.1)",
    badgeTextColorLight: "#2563eb",
    buttonBgColorLight: "#111827",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: null,
    button2TextColorLight: null,
    titleHighlightFrom: "#3b82f6",
    titleHighlightTo: "#06b6d4",
    titleHighlightFromLight: "#2563eb",
    titleHighlightToLight: "#0891b2",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 2,
  },
  {
    name: "P3200 Endüstriyel Güç İstasyonu",
    badge: "Flagship",
    badgeIcon: "star",
    title: "Endüstriyel Güç, Taşınabilir Boyut",
    titleHighlight: "P3200 Power Station",
    subtitle: "",
    buttonText: "Keşfet",
    buttonLink: "/urun/p3200",
    buttonStyle: "PRIMARY" as const,
    button2Text: "",
    button2Link: "",
    button2Style: "SECONDARY" as const,
    desktopImage: "/sliders/slider-yatay-p3200.png",
    overlayColor: "#0a0a0a",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.75)",
    badgeBgColor: "rgba(234,179,8,0.2)",
    badgeTextColor: "#facc15",
    buttonBgColor: "#FFFFFF",
    buttonTextColor: "#000000",
    button2BgColor: null,
    button2TextColor: null,
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(234,179,8,0.15)",
    badgeTextColorLight: "#ca8a04",
    buttonBgColorLight: "#111827",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: null,
    button2TextColorLight: null,
    titleHighlightFrom: "#eab308",
    titleHighlightTo: "#f97316",
    titleHighlightFromLight: "#ca8a04",
    titleHighlightToLight: "#ea580c",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 3,
  },
  {
    name: "P3200 Maksimum Güç",
    badge: "3200W",
    badgeIcon: "zap",
    title: "Maksimum Güç Kapasitesi",
    titleHighlight: "P3200 ile Sınırları Aşın",
    subtitle: "",
    buttonText: "Detayları Gör",
    buttonLink: "/urun/p3200",
    buttonStyle: "PRIMARY" as const,
    button2Text: "Karşılaştır",
    button2Link: "/karsilastir",
    button2Style: "OUTLINE" as const,
    desktopImage: "/sliders/slider-yatay-p3200-2.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.8)",
    badgeBgColor: "rgba(249,115,22,0.2)",
    badgeTextColor: "#fb923c",
    buttonBgColor: "#f97316",
    buttonTextColor: "#FFFFFF",
    button2BgColor: "transparent",
    button2TextColor: "#FFFFFF",
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(249,115,22,0.1)",
    badgeTextColorLight: "#ea580c",
    buttonBgColorLight: "#ea580c",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: "transparent",
    button2TextColorLight: "#111827",
    titleHighlightFrom: "#f97316",
    titleHighlightTo: "#ef4444",
    titleHighlightFromLight: "#ea580c",
    titleHighlightToLight: "#dc2626",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 4,
  },
  {
    name: "Singo 2000 Pro",
    badge: "Outdoor",
    badgeIcon: "truck",
    title: "Outdoor Maceralar İçin",
    titleHighlight: "Singo 2000 Pro",
    subtitle: "",
    buttonText: "İncele",
    buttonLink: "/urun/singo-2000-pro",
    buttonStyle: "PRIMARY" as const,
    button2Text: "Tüm Outdoor Ürünleri",
    button2Link: "/kategori/outdoor",
    button2Style: "SECONDARY" as const,
    desktopImage: "/sliders/slider-yatay-singo2000pro.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.8)",
    badgeBgColor: "rgba(59,130,246,0.2)",
    badgeTextColor: "#60a5fa",
    buttonBgColor: "#3b82f6",
    buttonTextColor: "#FFFFFF",
    button2BgColor: "rgba(255,255,255,0.1)",
    button2TextColor: "#FFFFFF",
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(59,130,246,0.1)",
    badgeTextColorLight: "#2563eb",
    buttonBgColorLight: "#2563eb",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: "rgba(0,0,0,0.05)",
    button2TextColorLight: "#111827",
    titleHighlightFrom: "#3b82f6",
    titleHighlightTo: "#8b5cf6",
    titleHighlightFromLight: "#2563eb",
    titleHighlightToLight: "#7c3aed",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 5,
  },
  {
    name: "Solar Panel Çözümleri",
    badge: "Sürdürülebilir Enerji",
    badgeIcon: "zap",
    title: "Güneşin Gücüyle Şarj",
    titleHighlight: "Taşınabilir Solar Paneller",
    subtitle: "",
    buttonText: "Solar Panelleri Gör",
    buttonLink: "/kategori/gunes-panelleri",
    buttonStyle: "PRIMARY" as const,
    button2Text: "",
    button2Link: "",
    button2Style: "SECONDARY" as const,
    desktopImage: "/sliders/slider-yatay-solarpanel.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.8)",
    badgeBgColor: "rgba(34,197,94,0.2)",
    badgeTextColor: "#22c55e",
    buttonBgColor: "#22c55e",
    buttonTextColor: "#FFFFFF",
    button2BgColor: null,
    button2TextColor: null,
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(34,197,94,0.1)",
    badgeTextColorLight: "#16a34a",
    buttonBgColorLight: "#16a34a",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: null,
    button2TextColorLight: null,
    titleHighlightFrom: "#22c55e",
    titleHighlightTo: "#10b981",
    titleHighlightFromLight: "#16a34a",
    titleHighlightToLight: "#059669",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 6,
  },
  {
    name: "Solar Enerji Sistemi",
    badge: "Off-Grid",
    badgeIcon: "zap",
    title: "Bağımsız Enerji Sistemi",
    titleHighlight: "Solar + Power Station",
    subtitle: "",
    buttonText: "Sistemleri İncele",
    buttonLink: "/kategori/gunes-panelleri",
    buttonStyle: "PRIMARY" as const,
    button2Text: "Nasıl Çalışır?",
    button2Link: "/blog",
    button2Style: "SECONDARY" as const,
    desktopImage: "/sliders/slider-yatay-solar.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.8)",
    badgeBgColor: "rgba(16,185,129,0.2)",
    badgeTextColor: "#34d399",
    buttonBgColor: "#10b981",
    buttonTextColor: "#FFFFFF",
    button2BgColor: "rgba(255,255,255,0.1)",
    button2TextColor: "#FFFFFF",
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(16,185,129,0.1)",
    badgeTextColorLight: "#059669",
    buttonBgColorLight: "#059669",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: "rgba(0,0,0,0.05)",
    button2TextColorLight: "#111827",
    titleHighlightFrom: "#10b981",
    titleHighlightTo: "#22c55e",
    titleHighlightFromLight: "#059669",
    titleHighlightToLight: "#16a34a",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 7,
  },
  {
    name: "Endüstriyel Eldivenler",
    badge: "İş Güvenliği",
    badgeIcon: "heart",
    title: "Profesyonel Koruma",
    titleHighlight: "Endüstriyel Eldivenler",
    subtitle: "",
    buttonText: "Ürünleri Gör",
    buttonLink: "/kategori/endustriyel-eldivenler",
    buttonStyle: "PRIMARY" as const,
    button2Text: "",
    button2Link: "",
    button2Style: "SECONDARY" as const,
    desktopImage: "/sliders/slider-yatay-gloves.png",
    overlayColor: "#000000",
    overlayOpacity: 0,
    overlayColorLight: "#FFFFFF",
    overlayOpacityLight: 0,
    titleColor: "#FFFFFF",
    subtitleColor: "rgba(255,255,255,0.8)",
    badgeBgColor: "rgba(168,85,247,0.2)",
    badgeTextColor: "#c084fc",
    buttonBgColor: "#FFFFFF",
    buttonTextColor: "#000000",
    button2BgColor: null,
    button2TextColor: null,
    titleColorLight: "#111827",
    subtitleColorLight: "rgba(75,85,99,1)",
    badgeBgColorLight: "rgba(168,85,247,0.1)",
    badgeTextColorLight: "#9333ea",
    buttonBgColorLight: "#111827",
    buttonTextColorLight: "#FFFFFF",
    button2BgColorLight: null,
    button2TextColorLight: null,
    titleHighlightFrom: "#a855f7",
    titleHighlightTo: "#ec4899",
    titleHighlightFromLight: "#9333ea",
    titleHighlightToLight: "#db2777",
    textAlign: "LEFT" as const,
    theme: "DARK" as const,
    order: 8,
  },
];

async function main() {
  console.log("🗑️  Eski slider'lar siliniyor...");
  await prisma.slider.deleteMany({});
  console.log("✅ Eski slider'lar silindi.");

  console.log("📦 Yeni slider'lar ekleniyor...");
  for (const slider of sliders) {
    const created = await prisma.slider.create({ data: slider });
    console.log(`  ✅ ${created.name} (order: ${created.order})`);
  }

  console.log(`\n🎉 Toplam ${sliders.length} slider eklendi.`);
}

main()
  .catch((e) => {
    console.error("❌ Seed hatası:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
