/**
 * Kullanım Senaryoları
 * Her senaryo için önceden tanımlanmış enerji, güç ve tipik cihaz listesi
 */

import { Scenario } from './types';

export const SCENARIOS: Scenario[] = [
  {
    id: 'custom',
    name: 'Özel Giriş',
    nameEn: 'Custom Entry',
    icon: 'Pencil',
    dailyEnergy: 0,
    maxPower: 0,
    description: 'Kendi değerlerinizi girin',
    descriptionEn: 'Enter your own values',
  },
  {
    id: 'student',
    name: 'Öğrenci',
    nameEn: 'Student',
    icon: 'GraduationCap',
    dailyEnergy: 500,
    maxPower: 1500,
    description: 'Laptop, telefon, tablet şarjı',
    descriptionEn: 'Laptop, phone, tablet charging',
    devices: [
      { id: 'laptop', name: 'Laptop', power: 60, hoursPerDay: 5, icon: 'laptop' },
      { id: 'phone-charge', name: 'Akıllı Telefon Şarjı', power: 15, hoursPerDay: 2, icon: 'smartphone' },
      { id: 'tablet-charge', name: 'Tablet / Kulaklık Şarjı', power: 15, hoursPerDay: 2, icon: 'tablet' },
      { id: 'desk-lamp', name: 'Masa Lambası (LED)', power: 10, hoursPerDay: 4, icon: 'led-lamp' },
      { id: 'bt-speaker', name: 'Bluetooth Hoparlör', power: 10, hoursPerDay: 4, icon: 'bluetooth-speaker' },
      { id: 'kettle-short', name: 'Su Isıtıcı (Kettle)', power: 1500, hoursPerDay: 0.05, icon: 'electric-kettle', note: 'Kısa süreli (3 dk)' },
    ],
  },
  {
    id: 'camp-2',
    name: 'Kamp (2 Kişi)',
    nameEn: 'Camping (2 People)',
    icon: 'Tent',
    dailyEnergy: 800,
    maxPower: 600,
    description: 'Aydınlatma, telefon, mini buzdolabı',
    descriptionEn: 'Lighting, phone, mini fridge',
    devices: [
      { id: 'camp-fridge', name: 'Kamp Buzdolabı (12V)', power: 45, hoursPerDay: 8, icon: 'mini-fridge', note: 'Aktif çalışma' },
      { id: 'phones-2', name: 'Telefonlar', power: 15, hoursPerDay: 2, quantity: 2, icon: 'smartphone' },
      { id: 'camp-light', name: 'Kamp Alanı Aydınlatması (LED)', power: 15, hoursPerDay: 6, icon: 'led-lamp' },
      { id: 'air-pump', name: 'Şişme Yatak Pompası', power: 120, hoursPerDay: 0.2, icon: 'pump', note: '12 dk' },
      { id: 'camp-coffee', name: 'Kahve Makinesi (Kamp Tipi)', power: 600, hoursPerDay: 0.3, icon: 'coffee-maker', note: '18 dk' },
      { id: 'headlamp', name: 'Şarjlı El Feneri / Kafa Lambası', power: 10, hoursPerDay: 2, icon: 'flashlight' },
    ],
  },
  {
    id: 'caravan',
    name: 'Karavan',
    nameEn: 'Caravan',
    icon: 'Caravan',
    dailyEnergy: 1500,
    maxPower: 1500,
    description: 'Tam donanımlı karavan kullanımı',
    descriptionEn: 'Fully equipped caravan usage',
    devices: [
      { id: 'caravan-fridge', name: 'Karavan Buzdolabı (A Sınıfı)', power: 60, hoursPerDay: 8, icon: 'mini-fridge', note: 'Aktif çalışma' },
      { id: 'water-pump', name: 'Su Pompası (Hidrofor)', power: 45, hoursPerDay: 1, icon: 'pump' },
      { id: 'tv-caravan', name: 'TV / Monitör', power: 50, hoursPerDay: 4, icon: 'tv' },
      { id: 'caravan-led', name: 'Karavan İçi LED Aydınlatma', power: 20, hoursPerDay: 5, icon: 'led-lamp' },
      { id: 'hair-dryer', name: 'Saç Kurutma Makinesi (Fön)', power: 1500, hoursPerDay: 0.1, icon: 'hair-dryer', note: '6 dk' },
      { id: 'kettle-caravan', name: 'Kettle / Çay Makinesi', power: 1000, hoursPerDay: 0.3, icon: 'electric-kettle', note: '18 dk' },
      { id: 'chargers-multi', name: 'Telefon / Tablet Şarjları', power: 20, hoursPerDay: 4, icon: 'smartphone' },
      { id: 'laptop-caravan', name: 'Dizüstü Bilgisayar', power: 60, hoursPerDay: 2, icon: 'laptop' },
    ],
  },
  {
    id: 'emergency-home',
    name: 'Acil Ev Kullanımı',
    nameEn: 'Emergency Home',
    icon: 'Home',
    dailyEnergy: 600,
    maxPower: 100,
    description: 'Elektrik kesintisi için temel ihtiyaçlar',
    descriptionEn: 'Basic needs for power outage',
    devices: [
      { id: 'home-fridge', name: 'Ev Tipi Buzdolabı (A+++)', power: 100, hoursPerDay: 3, icon: 'fridge', note: 'Kısa kesinti' },
      { id: 'router-home', name: 'Modem / Router', power: 15, hoursPerDay: 10, icon: 'router' },
      { id: 'family-chargers', name: 'Telefon Şarjları (Ailecek)', power: 15, hoursPerDay: 4, icon: 'smartphone' },
      { id: 'room-lights', name: 'Temel Oda Aydınlatması (2 Ampul)', power: 18, hoursPerDay: 4, icon: 'led-lamp' },
      { id: 'emergency-radio', name: 'Şarjlı Pilli Radyo / El Feneri', power: 5, hoursPerDay: 2, icon: 'radio' },
    ],
  },
  {
    id: 'drone',
    name: 'Drone Çekimi',
    nameEn: 'Drone Filming',
    icon: 'Camera',
    dailyEnergy: 1200,
    maxPower: 120,
    description: 'Drone bataryaları, kamera ekipmanı',
    descriptionEn: 'Drone batteries, camera equipment',
    devices: [
      { id: 'drone-charger', name: 'Drone Batarya Şarj İstasyonu', power: 120, hoursPerDay: 5, icon: 'drone' },
      { id: 'cam-batt', name: 'Kamera ve Gimbal Bataryaları', power: 45, hoursPerDay: 4, icon: 'camera' },
      { id: 'edit-laptop', name: 'Veri Aktarımı / Kurgu Laptopu', power: 80, hoursPerDay: 4, icon: 'laptop' },
      { id: 'field-monitor', name: 'Saha Monitörü (Yönetmen için)', power: 25, hoursPerDay: 4, icon: 'monitor' },
      { id: 'walkie-talkie', name: 'Telsizler (Ekip İletişimi)', power: 15, hoursPerDay: 2, icon: 'walkie' },
    ],
  },
  {
    id: 'party',
    name: 'Parti Devam Etsin',
    nameEn: 'Keep the Party Going',
    icon: 'Music',
    dailyEnergy: 900,
    maxPower: 400,
    description: 'Müzik sistemi, aydınlatma',
    descriptionEn: 'Music system, lighting',
    devices: [
      { id: 'pa-speaker', name: 'Taşınabilir Aktif Ses Sistemi', power: 120, hoursPerDay: 4, icon: 'bluetooth-speaker' },
      { id: 'smoke-machine', name: 'Duman / Sis Makinesi', power: 400, hoursPerDay: 0.5, icon: 'smoke', note: 'Aralıklı' },
      { id: 'dj-mixer', name: 'DJ Mikseri / Kontrolcü', power: 25, hoursPerDay: 4, icon: 'music' },
      { id: 'party-lights', name: 'Dinamik Lazer / LED Işıklar', power: 30, hoursPerDay: 4, icon: 'party-light' },
      { id: 'org-phones', name: 'Organizasyon Ekibi Telefonları', power: 15, hoursPerDay: 2, icon: 'smartphone' },
    ],
  },
  {
    id: 'outdoor-event',
    name: 'Outdoor Etkinlik',
    nameEn: 'Outdoor Event',
    icon: 'TreePine',
    dailyEnergy: 2000,
    maxPower: 250,
    description: 'Büyük açık hava etkinlikleri',
    descriptionEn: 'Large outdoor events',
    devices: [
      { id: 'pa-system', name: 'PA Anons ve Müzik Sistemi', power: 250, hoursPerDay: 4, icon: 'bluetooth-speaker' },
      { id: 'projector', name: 'Projektör / Büyük Ekran TV', power: 150, hoursPerDay: 3, icon: 'projector' },
      { id: 'drink-cooler', name: 'İçecek Soğutucu Dolap', power: 80, hoursPerDay: 5, icon: 'fridge', note: 'Aktif çalışma' },
      { id: 'area-lights', name: 'Çevre Aydınlatma Direkleri (LED)', power: 80, hoursPerDay: 3, icon: 'led-lamp' },
    ],
  },
  {
    id: 'remote-work',
    name: 'Uzaktan Çalışma',
    nameEn: 'Remote Work',
    icon: 'Laptop',
    dailyEnergy: 600,
    maxPower: 600,
    description: 'Laptop, monitor, internet ekipmanı',
    descriptionEn: 'Laptop, monitor, internet equipment',
    devices: [
      { id: 'work-laptop', name: 'İş Bilgisayarı (Laptop)', power: 65, hoursPerDay: 6, icon: 'laptop' },
      { id: 'ext-monitor', name: 'Harici Monitör (Taşınabilir)', power: 30, hoursPerDay: 4, icon: 'monitor' },
      { id: 'mifi-modem', name: '4G/5G Taşınabilir Modem', power: 10, hoursPerDay: 6, icon: 'router' },
      { id: 'phone-headset', name: 'Telefon ve Kulaklık Şarjı', power: 15, hoursPerDay: 2, icon: 'smartphone' },
      { id: 'capsule-coffee', name: 'Kahve Makinesi (Kapsüllü)', power: 600, hoursPerDay: 0.1, icon: 'coffee-maker', note: '6 dk' },
    ],
  },
  {
    id: 'boat-fishing',
    name: 'Tekne / Balıkçılık',
    nameEn: 'Boat / Fishing',
    icon: 'Ship',
    dailyEnergy: 1000,
    maxPower: 500,
    description: 'Denizde enerji ihtiyaçları',
    descriptionEn: 'Marine power needs',
    devices: [
      { id: 'fish-finder', name: 'Balık Bulucu (Sonar)', power: 25, hoursPerDay: 8, icon: 'sonar' },
      { id: 'boat-fridge', name: 'Tekne Buzdolabı', power: 45, hoursPerDay: 8, icon: 'mini-fridge', note: 'Aktif çalışma' },
      { id: 'electric-winch', name: 'Elektrikli Çıkrık (Derin Su Avı)', power: 120, hoursPerDay: 2, icon: 'wrench' },
      { id: 'nav-lights', name: 'Seyir Fenerleri', power: 15, hoursPerDay: 6, icon: 'led-lamp' },
      { id: 'vhf-radio', name: 'VHF Telsiz ve Telefonlar', power: 10, hoursPerDay: 3, icon: 'walkie' },
      { id: 'small-kettle', name: 'Küçük Su Isıtıcı', power: 500, hoursPerDay: 0.1, icon: 'electric-kettle', note: 'Sıcak içecek' },
    ],
  },
  {
    id: 'field-work',
    name: 'Arazi Çalışması',
    nameEn: 'Field Work',
    icon: 'Wrench',
    dailyEnergy: 1800,
    maxPower: 150,
    description: 'Profesyonel saha ekipmanları',
    descriptionEn: 'Professional field equipment',
    devices: [
      { id: 'toughbook', name: 'Endüstriyel Laptop (Toughbook)', power: 90, hoursPerDay: 6, icon: 'laptop' },
      { id: 'survey-device', name: 'Ölçüm Cihazları (Total Station)', power: 50, hoursPerDay: 4, icon: 'survey' },
      { id: 'power-tools', name: 'Şarjlı El Aletleri (Matkap vb.)', power: 150, hoursPerDay: 3, icon: 'wrench', note: 'Şarj süresi' },
      { id: 'field-cooler', name: 'Saha Tipi Kompresörlü Soğutucu', power: 50, hoursPerDay: 8, icon: 'mini-fridge', note: 'Aktif çalışma' },
      { id: 'mapping-drone', name: 'Drone / Haritalama İHA\'sı', power: 100, hoursPerDay: 2, icon: 'drone' },
    ],
  },
  {
    id: 'small-business',
    name: 'Küçük İşletme',
    nameEn: 'Small Business',
    icon: 'Store',
    dailyEnergy: 2500,
    maxPower: 600,
    description: 'Dükkan, stant, mobil ofis',
    descriptionEn: 'Shop, booth, mobile office',
    devices: [
      { id: 'commercial-cooler', name: 'Ticari İçecek Dolabı', power: 120, hoursPerDay: 8, icon: 'fridge', note: 'Aktif çalışma' },
      { id: 'sign-lighting', name: 'Tabela ve Vitrin Aydınlatması', power: 100, hoursPerDay: 8, icon: 'led-lamp' },
      { id: 'pos-terminal', name: 'Yazar Kasa / POS Cihazı', power: 20, hoursPerDay: 10, icon: 'pos' },
      { id: 'auto-tea', name: 'Çay Makinesi (Otomatik)', power: 600, hoursPerDay: 0.5, icon: 'electric-kettle', note: 'Isıtma/Koruma' },
      { id: 'bg-music', name: 'Müzik Yayını (Hoparlör)', power: 30, hoursPerDay: 8, icon: 'bluetooth-speaker' },
    ],
  },
  {
    id: 'photography',
    name: 'Fotoğrafçılık',
    nameEn: 'Photography',
    icon: 'Camera',
    dailyEnergy: 800,
    maxPower: 1500,
    description: 'Kamera, flash, laptop şarjı',
    descriptionEn: 'Camera, flash, laptop charging',
    devices: [
      { id: 'flash-led', name: 'Paraflaş / LED Sürekli Işık', power: 120, hoursPerDay: 3, icon: 'led-lamp' },
      { id: 'cam-charger', name: 'Kamera ve Batarya Şarj İstasyonları', power: 35, hoursPerDay: 4, icon: 'camera' },
      { id: 'tether-laptop', name: 'Laptop (Tethered - Anlık Kontrol)', power: 70, hoursPerDay: 4, icon: 'laptop' },
      { id: 'model-dryer', name: 'Saç Kurutma/Fön (Model hazırlığı)', power: 1500, hoursPerDay: 0.05, icon: 'hair-dryer', note: '3 dk' },
    ],
  },
  {
    id: 'medical',
    name: 'Medikal Cihazlar',
    nameEn: 'Medical Devices',
    icon: 'Heart',
    dailyEnergy: 400,
    maxPower: 60,
    description: 'CPAP, nebulizatör, oksijen',
    descriptionEn: 'CPAP, nebulizer, oxygen',
    devices: [
      { id: 'cpap', name: 'CPAP Cihazı (Uyku Apnesi)', power: 45, hoursPerDay: 8, icon: 'cpap' },
      { id: 'nebulizer', name: 'Nebulizatör (Hava Makinesi)', power: 60, hoursPerDay: 0.5, icon: 'medical' },
      { id: 'vitals-monitor', name: 'Taşınabilir Tansiyon/Şeker Ölçer', power: 5, hoursPerDay: 1, icon: 'medical' },
      { id: 'med-phone', name: 'Telefon Şarjı', power: 15, hoursPerDay: 1, icon: 'smartphone' },
    ],
  },
  {
    id: 'music-band',
    name: 'Müzik Grubu',
    nameEn: 'Music Band',
    icon: 'Music',
    dailyEnergy: 1500,
    maxPower: 400,
    description: 'Amplifikatör, mikser, hoparlör',
    descriptionEn: 'Amplifier, mixer, speakers',
    devices: [
      { id: 'instr-amp', name: 'Enstrüman Amfileri (Gitar/Bas)', power: 120, hoursPerDay: 3, quantity: 2, icon: 'music' },
      { id: 'pa-vocal', name: 'PA Vokal ve Klavye Sistemi', power: 200, hoursPerDay: 3, icon: 'bluetooth-speaker' },
      { id: 'mixer-synth', name: 'Mikser, Synth ve Pedallar', power: 40, hoursPerDay: 3, icon: 'music' },
      { id: 'band-smoke', name: 'Duman / Sis Makinesi', power: 400, hoursPerDay: 0.5, icon: 'smoke' },
      { id: 'stage-lights', name: 'Sahne Işıkları (LED)', power: 80, hoursPerDay: 3, icon: 'party-light' },
    ],
  },
  {
    id: 'food-truck',
    name: 'Yemek Tırı',
    nameEn: 'Food Truck',
    icon: 'UtensilsCrossed',
    dailyEnergy: 3000,
    maxPower: 200,
    description: 'Buzdolabı, ızgara, aydınlatma',
    descriptionEn: 'Fridge, grill, lighting',
    devices: [
      { id: 'counter-fridge', name: 'Endüstriyel Tip Tezgah Altı Dolap', power: 180, hoursPerDay: 8, icon: 'fridge', note: 'Aktif çalışma' },
      { id: 'ventilation', name: 'Aspiratör / Havalandırma', power: 150, hoursPerDay: 6, icon: 'fan' },
      { id: 'truck-lights', name: 'Tır İçi ve Menü Aydınlatması', power: 80, hoursPerDay: 6, icon: 'led-lamp' },
      { id: 'pos-tablets', name: 'POS / Adisyon Tabletleri', power: 20, hoursPerDay: 10, icon: 'tablet' },
    ],
  },
  {
    id: 'security',
    name: 'Güvenlik Sistemi',
    nameEn: 'Security System',
    icon: 'Shield',
    dailyEnergy: 300,
    maxPower: 20,
    description: 'Kamera, NVR, internet',
    descriptionEn: 'Camera, NVR, internet',
    devices: [
      { id: 'nvr', name: 'NVR Kayıt Cihazı ve Harddisk', power: 15, hoursPerDay: 10, icon: 'security' },
      { id: 'security-cams', name: 'Güvenlik Kameraları', power: 10, hoursPerDay: 10, icon: 'security', note: '4 adet toplam' },
      { id: 'security-modem', name: 'Modem / İnternet İletişimi', power: 10, hoursPerDay: 10, icon: 'router' },
      { id: 'sensor-panel', name: 'Hareket / Kapı Sensörleri Paneli', power: 5, hoursPerDay: 10, icon: 'sensor' },
    ],
  },
  {
    id: 'garden',
    name: 'Bahçe / Hobi',
    nameEn: 'Garden / Hobby',
    icon: 'Flower2',
    dailyEnergy: 500,
    maxPower: 200,
    description: 'Aletler, aydınlatma, pompa',
    descriptionEn: 'Tools, lighting, pump',
    devices: [
      { id: 'mower-charger', name: 'Şarjlı Çim Biçme Batarya İstasyonu', power: 200, hoursPerDay: 1.5, icon: 'mower' },
      { id: 'saw-charger', name: 'Dal Budama/Testere Batarya Şarjı', power: 100, hoursPerDay: 1, icon: 'wrench' },
      { id: 'pond-pump', name: 'Süs Havuzu Su Pompası', power: 30, hoursPerDay: 3, icon: 'pump' },
      { id: 'garden-tools', name: 'Şarjlı El Aletleri (Matkap vs.)', power: 50, hoursPerDay: 1, icon: 'wrench' },
    ],
  },
  {
    id: 'animal-farm',
    name: 'Hayvan Çiftliği',
    nameEn: 'Animal Farm',
    icon: 'Wheat',
    dailyEnergy: 3000,
    maxPower: 750,
    description: 'Ağıl/Ahır elektrifikasyonu ve sağım',
    descriptionEn: 'Barn electrification and milking',
    devices: [
      { id: 'milking-machine', name: 'Süt Sağım Makinesi', power: 750, hoursPerDay: 1.5, icon: 'pump', note: 'Tek/Çift Güğüm' },
      { id: 'trough-pump', name: 'Su Pompası (Sulukları Doldurma)', power: 500, hoursPerDay: 1, icon: 'pump' },
      { id: 'electric-fence', name: 'Elektrikli Çit Cihazı (Şoklayıcı)', power: 10, hoursPerDay: 24, icon: 'sensor' },
      { id: 'barn-lights', name: 'Ahır Aydınlatması', power: 100, hoursPerDay: 6, icon: 'led-lamp' },
      { id: 'farm-security', name: 'Çiftlik Güvenlik Kameraları ve Sensör', power: 20, hoursPerDay: 24, icon: 'security' },
      { id: 'vet-trimmer', name: 'Veteriner Tıraş/Bakım Makinesi', power: 50, hoursPerDay: 0.5, icon: 'trimmer' },
    ],
  },
];

export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find(s => s.id === id);
}

export function getScenarioName(scenario: Scenario, language: 'tr' | 'en'): string {
  return language === 'en' ? scenario.nameEn : scenario.name;
}

export function getScenarioDescription(scenario: Scenario, language: 'tr' | 'en'): string | undefined {
  return language === 'en' ? scenario.descriptionEn : scenario.description;
}
